export const actions = {
  TODO_DESTROY_ACTION: 'TODO_DESTROY_ACTION',
  TODO_TOGGLE_STATUS_ACTION: 'TODO_TOGGLE_STATUS_ACTION',
  TODO_REMOVE_COMPLETE_ACTION: 'TODO_REMOVE_COMPLETE_ACTION',
  TODO_CREATE_ACTION: 'TODO_CREATE_ACTION',
  TODO_EDIT_ACTION: 'TODO_EDIT_ACTION'
}
